version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: helpdesk_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: helpdesk_mini

  backend:
    build: .
    container_name: helpdesk_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/helpdesk_mini
      JWT_SECRET: your-super-secure-production-jwt-secret-key-here
      PORT: 5000
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: helpdesk_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: