services:
  # Backend API Service
  - type: web
    name: helpdesk-mini-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: helpdesk-mini-backend
          property: port
      - key: MONGODB_URI
        sync: false  # You'll add this manually in Render dashboard
      - key: JWT_SECRET
        sync: false  # You'll add this manually in Render dashboard